name: Deploy webfic-sedai

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ Check out the repo
      - uses: actions/checkout@v4

      # 2 ▸ Setup Bun
      - uses: oven-sh/setup-bun@v2

      # 3 ▸ Install dependencies
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # 4 ▸ Build the app
      - name: Build the app
        run: bun run build

      # 5 ▸ Clean export directory on the server
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -euo pipefail
            mkdir -p "${{ secrets.EXPORT_DIR }}"
            rm -rf "${{ secrets.EXPORT_DIR }}"/*

      # 6 ▸ Upload build to server
      - uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "dist"
          target: "${{ secrets.EXPORT_DIR }}"

      # 7 ▸ Flatten build directory
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -euo pipefail
            mv "${{ secrets.EXPORT_DIR }}/dist/"* "${{ secrets.EXPORT_DIR }}/"
            rm -rf "${{ secrets.EXPORT_DIR }}/dist"
